From python
##it will check for python image in docker engine if not present then will pull from DockerHub

MAINTAINER dipesh016@gmail.com , 92456789135
##Developer of docker image this keyword is exceptional

RUN mkdir /mycode
##run instruction can execute any linux command inside my docker image that i am going to create

COPY hello.py /mycode/hello.py
##it will copy code from system location to docker image

CMD python /mycode/hello.py
##this will run the code as default parent process



